# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftSearch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftSearch
  pod 'NCMB', :git => 'https://github.com/NIFCLOUD-mbaas/ncmb_swift.git'

end
